#!/usr/bin/env bash
set -euo pipefail

# Discover Proxmox management IPs by probing which host runs which VMIDs.
# Run from a machine on the 192.168.11.x LAN with SSH to Proxmox nodes.
#
# Usage:
#   bash scripts/discover-proxmox-management-ips.sh
#   PROXMOX_SSH_USER=root bash scripts/discover-proxmox-management-ips.sh --write

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT/deploy/proxmox/github-secrets.env"
WRITE=false
SSH_USER="${PROXMOX_SSH_USER:-root}"

for arg in "$@"; do
  case "$arg" in
    --write) WRITE=true ;;
  esac
done

# Hostnames from ALL_VMIDS_ENDPOINTS + common management IP guesses
CANDIDATES=(
  r630-04
  r630-03
  r630-04.local
  r630-03.local
  192.168.11.4
  192.168.11.3
  192.168.11.104
  192.168.11.103
  192.168.11.10
  192.168.11.11
  192.168.11.14
  192.168.11.13
)

ssh_probe() {
  local host="$1"
  local cmd="$2"
  if [ -n "${PROXMOX_SSH_PRIVATE_KEY:-}" ]; then
    ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=5 -o BatchMode=yes \
      -i <(printf '%s' "$PROXMOX_SSH_PRIVATE_KEY") \
      "${SSH_USER}@${host}" "$cmd" 2>/dev/null
  elif [ -n "${PROXMOX_SSH_PASSWORD:-}" ] && command -v sshpass >/dev/null 2>&1; then
    sshpass -p "$PROXMOX_SSH_PASSWORD" ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=5 \
      "${SSH_USER}@${host}" "$cmd" 2>/dev/null
  else
    ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=5 -o BatchMode=yes \
      "${SSH_USER}@${host}" "$cmd" 2>/dev/null
  fi
}

R630_04_HOST=""
R630_03_HOST=""

echo "==> Discovering Proxmox management hosts (VMID 5824 on r630-04, 5825 on r630-03)"
echo ""

for host in "${CANDIDATES[@]}"; do
  if ! ssh_probe "$host" "command -v pct >/dev/null && pct list"; then
    continue
  fi
  list="$(ssh_probe "$host" "pct list")"
  if [ -z "$R630_04_HOST" ] && grep -qE '[[:space:]]5824[[:space:]]' <<<"$list"; then
    R630_04_HOST="$host"
    echo "  found r630-04 (5824) on ${SSH_USER}@${host}"
  fi
  if [ -z "$R630_03_HOST" ] && grep -qE '[[:space:]]5825[[:space:]]' <<<"$list"; then
    R630_03_HOST="$host"
    echo "  found r630-03 (5825) on ${SSH_USER}@${host}"
  fi
  if [ -n "$R630_04_HOST" ] && [ -n "$R630_03_HOST" ]; then
    break
  fi
done

echo ""
if [ -z "$R630_04_HOST" ] || [ -z "$R630_03_HOST" ]; then
  echo "Could not auto-discover both nodes."
  echo "  r630-04 (5824): ${R630_04_HOST:-NOT FOUND}"
  echo "  r630-03 (5825): ${R630_03_HOST:-NOT FOUND}"
  echo ""
  echo "Set manually in deploy/proxmox/github-secrets.env:"
  echo "  export PROXMOX_R630_04_HOST=\"<r630-04-mgmt-ip>\""
  echo "  export PROXMOX_R630_03_HOST=\"<r630-03-mgmt-ip>\""
  exit 1
fi

echo "Discovered:"
echo "  PROXMOX_R630_04_HOST=${R630_04_HOST}"
echo "  PROXMOX_R630_03_HOST=${R630_03_HOST}"

if $WRITE; then
  mkdir -p "$(dirname "$OUT_FILE")"
  cat > "$OUT_FILE" <<EOF
# Auto-generated by scripts/discover-proxmox-management-ips.sh
export PROXMOX_R630_04_HOST="${R630_04_HOST}"
export PROXMOX_R630_03_HOST="${R630_03_HOST}"
export PROXMOX_SSH_USER="${SSH_USER}"
export GITHUB_REPOSITORY="zaragoza444/nova-trust"
# export PROXMOX_SSH_PRIVATE_KEY="\$(cat ~/.ssh/id_ed25519)"
EOF
  echo ""
  echo "Wrote ${OUT_FILE}"
  echo "Add PROXMOX_SSH_PRIVATE_KEY, then:"
  echo "  source deploy/proxmox/github-secrets.env"
  echo "  bash scripts/setup-proxmox-github-secrets.sh --test --apply"
fi
