#!/usr/bin/env bash
set -euo pipefail

# Wire Nova Trust internationally:
# - TRON basement + Ethereum + BNB public RPCs
# - Nova One permissioned settlement on 22016
# - Public dashboard/API exposure via nginx on the VPS
#
# Usage:
#   bash scripts/wire-international-vps.sh

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INTERNATIONAL_ENV="${NOVA_INTERNATIONAL_ENV_FILE:-$ROOT/deploy/.env.international}"
PRODUCTION_ENV="${NOVA_PRODUCTION_ENV_FILE:-$ROOT/deploy/.env.production}"
NGINX_SITE="${NOVA_NGINX_SITE:-/etc/nginx/sites-available/nova-trust}"

echo "==> Wiring Nova Trust internationally"

if [ ! -f "$INTERNATIONAL_ENV" ]; then
  cp "$ROOT/deploy/international.env.example" "$INTERNATIONAL_ENV"
  echo "Created ${INTERNATIONAL_ENV}"
fi

set -a
# shellcheck disable=SC1090
source "$INTERNATIONAL_ENV"
set +a

echo "==> Verifying international public network RPC connectivity"
bash "$ROOT/scripts/wire-multi-network-vps.sh"

echo "==> Merging international env into production runtime env"
{
  echo "# Generated by scripts/wire-international-vps.sh"
  cat "$ROOT/deploy/production.env.example"
  echo ""
  echo "# International wiring overrides"
  cat "$INTERNATIONAL_ENV"
} > "$PRODUCTION_ENV"

if command -v nginx >/dev/null 2>&1 && [ "${NOVA_INTERNATIONAL_NGINX:-true}" = "true" ]; then
  echo "==> Installing nginx site for international dashboard/API access"
  if [ -w /etc/nginx/sites-available ] 2>/dev/null; then
    cp "$ROOT/deploy/nginx/nova-trust.conf" "$NGINX_SITE"
    ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/nova-trust
    nginx -t
    if command -v systemctl >/dev/null 2>&1; then
      systemctl reload nginx
    else
      service nginx reload
    fi
  elif command -v sudo >/dev/null 2>&1; then
    sudo cp "$ROOT/deploy/nginx/nova-trust.conf" "$NGINX_SITE"
    sudo ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/nova-trust
    sudo nginx -t
    sudo systemctl reload nginx
  else
    echo "nginx found but cannot install site without sudo; copy deploy/nginx/nova-trust.conf manually"
  fi
else
  echo "nginx not installed; public international URLs will use direct ports 3000/4000"
fi

echo "==> Starting production stack"
export GO_LIVE_SKIP_BOOTSTRAP="${GO_LIVE_SKIP_BOOTSTRAP:-true}"
bash "$ROOT/scripts/go-live.sh"

echo "==> International wiring verification"
npm run build --workspace @nova/api
curl -sf -H "x-nova-role: AUDITOR" "http://127.0.0.1:4000/api/networks/international" | tee /tmp/nova-international-wiring.json
echo ""

PUBLIC_HOST="${NOVA_PUBLIC_HOST:-51.75.64.28}"
PUBLIC_SCHEME="${NOVA_PUBLIC_SCHEME:-http}"
if [ "${NOVA_INTERNATIONAL_NGINX:-true}" = "true" ]; then
  DASHBOARD_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}"
  API_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}"
else
  DASHBOARD_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}:3000"
  API_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}:4000"
fi

cat <<EOF

Nova Trust wired internationally

  Public dashboard  ${DASHBOARD_URL}
  Public API        ${API_URL}
  International     ${API_URL}/api/networks/international
  Multi-network     ${API_URL}/api/networks/health
  Go-live status    ${API_URL}/api/go-live/status

  Public networks   TRON · Ethereum · BNB Smart Chain
  Settlement chain  Nova One (22016)
  Clone tokens      USDT · ETH · BTC · BNB · USDC · ...

EOF
