#!/usr/bin/env bash
set -euo pipefail

# Wire Z Ecosystem for public VPS access:
# - TRON + Ethereum + BNB public RPCs
# - Z Blockchain settlement on 44002
# - Public dashboard/API via nginx on port 80
#
# Usage:
#   bash scripts/wire-z-vps.sh

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
Z_ENV="${Z_PRODUCTION_ENV_FILE:-$ROOT/deploy/.env.z-production}"
Z_EXAMPLE="$ROOT/deploy/z-production.env.example"
NGINX_SITE="${Z_NGINX_SITE:-/etc/nginx/sites-available/z-stack}"

echo "==> Wiring Z Ecosystem for public VPS access"

if [ ! -f "$Z_ENV" ]; then
  cp "$Z_EXAMPLE" "$Z_ENV"
  echo "Created ${Z_ENV}"
fi

PUBLIC_HOST="${Z_PUBLIC_HOST:-51.75.64.28}"
PUBLIC_SCHEME="${Z_PUBLIC_SCHEME:-http}"

echo "==> Verifying international public network RPC connectivity"
bash "$ROOT/scripts/wire-multi-network-vps.sh"

echo "==> Merging public VPS settings into Z production runtime env"
{
  echo "# Generated by scripts/wire-z-vps.sh"
  cat "$Z_EXAMPLE"
  echo ""
  echo "# Public VPS wiring overrides"
  echo "export Z_PUBLIC_HOST=\"${PUBLIC_HOST}\""
  echo "export Z_PUBLIC_SCHEME=\"${PUBLIC_SCHEME}\""
  echo "export Z_INTERNATIONAL_NGINX=\"true\""
  echo "export Z_API_HOST=\"0.0.0.0\""
  echo "export Z_PUBLIC_DASHBOARD_URL=\"${PUBLIC_SCHEME}://${PUBLIC_HOST}\""
  echo "export Z_PUBLIC_API_URL=\"${PUBLIC_SCHEME}://${PUBLIC_HOST}\""
  echo "export Z_API_URL=\"http://127.0.0.1:4100\""
  echo "export NEXT_PUBLIC_Z_API_URL=\"${PUBLIC_SCHEME}://${PUBLIC_HOST}\""
  echo "export Z_CORS_ORIGIN=\"${PUBLIC_SCHEME}://${PUBLIC_HOST},http://127.0.0.1:3100\""
} > "$Z_ENV"

install_nginx_site() {
  local site_path="$1"
  local site_name="$2"
  if [ -w /etc/nginx/sites-available ] 2>/dev/null; then
    cp "$ROOT/deploy/nginx/z-stack.conf" "$site_path"
    ln -sf "$site_path" "/etc/nginx/sites-enabled/${site_name}"
    rm -f /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/nova-trust 2>/dev/null || true
    nginx -t
    if command -v systemctl >/dev/null 2>&1; then
      systemctl reload nginx
    else
      service nginx reload
    fi
  elif command -v sudo >/dev/null 2>&1; then
    sudo cp "$ROOT/deploy/nginx/z-stack.conf" "$site_path"
    sudo ln -sf "$site_path" "/etc/nginx/sites-enabled/${site_name}"
    sudo rm -f /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/nova-trust 2>/dev/null || true
    sudo nginx -t
    sudo systemctl reload nginx
  else
    echo "nginx found but cannot install site without sudo; copy deploy/nginx/z-stack.conf manually"
    return 1
  fi
}

if command -v nginx >/dev/null 2>&1 && [ "${Z_INTERNATIONAL_NGINX:-true}" = "true" ]; then
  echo "==> Installing nginx site for Z ecosystem public access"
  install_nginx_site "$NGINX_SITE" "z-stack" || true
else
  echo "nginx not installed; public URLs will use direct ports 3100/4100"
fi

echo "==> Starting Z ecosystem production stack"
export GO_LIVE_USE_DOCKER="${GO_LIVE_USE_DOCKER:-true}"
bash "$ROOT/scripts/z-go-live.sh"

echo "==> Z ecosystem wiring verification"
curl -sf -H "x-z-role: AUDITOR" "http://127.0.0.1:4100/api/go-live/status" | tee /tmp/z-go-live-status.json
echo ""

if [ "${Z_INTERNATIONAL_NGINX:-true}" = "true" ]; then
  DASHBOARD_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}"
  API_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}"
else
  DASHBOARD_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}:3100"
  API_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}:4100"
fi

cat <<EOF

Z Ecosystem wired for public VPS access

  Public Z Chart     ${DASHBOARD_URL}/zchart
  Public Z Trade     ${DASHBOARD_URL}/ztrade
  Public Z Swap      ${DASHBOARD_URL}/zswap
  Public Z Wallet    ${DASHBOARD_URL}/wallet
  Public Z Bank      ${DASHBOARD_URL}/zbank
  Public Z Chain     ${DASHBOARD_URL}/z-chain
  Public Z Bot       ${DASHBOARD_URL}/zbot
  Public API         ${API_URL}/api/go-live/status
  Z Bot status       ${API_URL}/api/zbot/status
  Health             ${API_URL}/health

  Public networks    TRON · Ethereum · BNB Smart Chain
  Settlement chain   Z Blockchain (44002)

EOF
