global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nova-besu
    static_configs:
      - targets:
          - validator-1:9545
          - validator-2:9545
          - validator-3:9545
          - validator-4:9545
          - rpc-1:9545
          - rpc-2:9545

  - job_name: nova-api
    static_configs:
      - targets:
          - api:4000

  - job_name: nova-indexer
    static_configs:
      - targets:
          - indexer:9464
